CREATE TABLE IF NOT EXISTS gigs (
    id    VARCHAR PRIMARY KEY NOT NULL,
    title VARCHAR NOT NULL,
    location  TEXT NOT NULL,
    date  TIMESTAMP NOT NULL,
    artist_id VARCHAR NOT NULL REFERENCES artists(id)
)
